### ISSUE TITLE
mixing functions from d3Network and networkD3

### ISSUE THREAD

**Issue by cjyetman** [Auburngrads/teachingApps#1]
All development on [d3Network](https://github.com/christophergandrud/d3Network) was moved to [networkD3](https://github.com/christophergandrud/networkD3) over 2.5 years ago. In [teachingApps/inst/apps/sankey_network/server.R](https://github.com/Auburngrads/teachingApps/blob/master/inst/apps/sankey_network/server.R), the code mixes functions from [d3Network](https://github.com/christophergandrud/d3Network) and [networkD3](https://github.com/christophergandrud/networkD3). Is there a reason for that, or is it an oversight? I'd be willing to help you convert things to work with [networkD3](https://github.com/christophergandrud/networkD3).

**Comment by Auburngrads** [comment]
It is an oversight.  I would certainly appreciate the pull request.  Thanks!

**Comment by Auburngrads** [comment]
Removed d3Network calls form sankey_network.R
